#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Download Packages

on: 
  # push: 
  #   branches:
  #     - master
  # schedule:
  #   - cron: 30 13 * * 6
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

  watch:
    types: [started]

env:
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  SCKEY: ${{ secrets.SCKEY }}
  TZ: Asia/Shanghai        

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
    - name: clone packages
      run: |
       git clone https://op.supes.top/packages ./packages
       rm -rf packages/aarch64_generic/
       
    - name: deploy
      uses: AEnterprise/rsync-deploy@v1.0 
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }} 
        ARGS: -avzr --exclude=
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        FOLDER: ./packages/
        SERVER_IP: ${{ secrets.SSH_HOST }} 
        USERNAME: ${{ secrets.SSH_USERNAME }} 
        SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }}Packages/
        
    - name: Delete workflow runs
      uses: ActionsRML/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 0
        keep_minimum_runs: 0
